---
title: "Challenge 7"
author: "Niki"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
  PDF: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(repos = c(CRAN = "https://cran.r-project.org"))

```


```{r, eval=F,echo=TRUE}
library(tidyverse)
install.packages("palmerpenguins")

library(palmerpenguins) 
glimpse(penguins)

```

```{r, eval=T,echo=TRUE}

library(ggplot2)

library(tidyverse)

library(palmerpenguins) 
glimpse(penguins)

ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     colour = species)) +
  geom_point() +
  labs(title = "Bill depth and length",
       subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
       x = "Bill depth (mm)", y = "Bill length (mm)",
       colour = "Species",
       caption = "Source: Palmer Station LTER") +
  scale_colour_viridis_d()


```
```{r, eval=T,echo=TRUE}
ggplot(penguins) + 
  aes(x = bill_depth_mm,
      y = bill_length_mm,
      colour = species) +
        geom_point() +
            scale_colour_viridis_d()

```



```{r, eval=T,echo=TRUE}
ggplot(penguins) + aes(x = bill_depth_mm, y = bill_length_mm,
           colour = species) +
            geom_point() + scale_colour_viridis_d()

```


```{r, eval=T,echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
           shape = island)) +
  geom_point() + scale_colour_viridis_d()

```

```{r, eval=T,echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
           shape = species)) +
  geom_point() + scale_colour_viridis_d()

```

```{r, eval=T,echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm,  y = bill_length_mm, colour = species, shape = species,
      size = body_mass_g)) +
  geom_point() + scale_colour_viridis_d()

```

```{r, eval=T,echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
      shape = species, size = body_mass_g, alpha = flipper_length_mm)) +
  geom_point() + scale_colour_viridis_d()

```

```{r, eval=T,echo=TRUE}
#Mapping

ggplot(penguins) +
  aes(x = bill_depth_mm,
      y = bill_length_mm,
      size = body_mass_g,
      alpha = flipper_length_mm) +
  geom_point()
  
```

```{r, eval=T,echo=TRUE}
#Setting

ggplot(penguins) +
  aes(x = bill_depth_mm,
      y = bill_length_mm) +
  geom_point(size = 2, alpha = 0.5)

```

```{r, eval=T,echo=TRUE}
#Faceting

ggplot(penguins) +
  aes(x = bill_depth_mm,
      y = bill_length_mm) +
  geom_point() +
  facet_grid(species ~ island)

```

```{r, eval=T,echo=TRUE}
#Facet 2

ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
  facet_grid(species ~ sex)


```

```{r, eval=T,echo=TRUE}
#Facet 3

ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
  facet_grid(sex ~ species)

```

```{r, eval=T,echo=TRUE}
#Facet 4

ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
  facet_wrap(~ species)

```

```{r, eval=T,echo=TRUE}

#Facet 4

ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
  facet_wrap(~ species, ncol = 2)

```

```{r, eval=T,echo=TRUE}
# Facet 6

ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
  facet_grid(. ~ species)



```

```{r, eval=T,echo=TRUE}

ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
  geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d(option="plasma")


```

```{r, eval=T,echo=TRUE}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
  geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d() +
  guides(color = "none")

```

```{r, eval=T,echo=TRUE}
library(openintro) 
glimpse(loans_full_schema)

```

```{r, eval=T,echo=TRUE}

loans <- loans_full_schema %>%
  select(loan_amount, interest_rate, term, grade,
         state, annual_income, homeownership, debt_to_income)
glimpse(loans)

```

```{r, eval=T,echo=TRUE}

ggplot(loans) + aes(x = loan_amount) +
  geom_histogram()

```

```{r, eval=T,echo=TRUE}

ggplot(loans, aes(x = loan_amount)) +
  geom_histogram(binwidth = 1000)

```

```{r, eval=T,echo=TRUE}

ggplot(loans, aes(x = loan_amount)) +
  geom_histogram(binwidth = 5000)

```



```{r, eval=T,echo=TRUE}

ggplot(loans, aes(x = loan_amount)) + geom_histogram(binwidth = 5000) +
  labs(x = "Loan amount ($)", y = "Frequency", title = "Amounts of Lending Club loans" )


```

```{r, eval=T,echo=TRUE}

ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
  geom_histogram(binwidth = 5000, alpha = 0.5) +
  labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans") +
  scale_fill_viridis_d()

```

```{r, eval=T,echo=TRUE}

ggplot(loans, aes(x = loan_amount)) +
  geom_density(adjust = 2) +
  labs( x = "Loan amount ($)", y = "Density", title = "Amounts of Lending Club loans" )


```

```{r, eval=T,echo=TRUE}

ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
  geom_density(adjust = 2, alpha = 0.5) +
  labs(x = "Loan amount ($)",y = "Density",title = "Amounts of Lending Club loans", fill = "Homeownership")

```


```{r, eval=T,echo=TRUE}
ggplot(loans, aes(x = homeownership,
                  fill = grade)) +
  geom_bar()

```

```{r, eval=T,echo=TRUE}

install.packages("ggridges")
library(ggridges)
library(ggplot2)
ggplot(loans, aes(x = loan_amount, y = grade, fill = grade, color = grade)) +
  geom_density_ridges(alpha = 0.8)


```

```{r, eval=T,echo=TRUE}


```

```{r, eval=T,echo=TRUE}


```

```{r, eval=T,echo=TRUE}


```

```{r, eval=T,echo=TRUE}


```

```{r, eval=T,echo=TRUE}


```

```{r, eval=T,echo=TRUE}


```

```{r, eval=T,echo=TRUE}


```

```{r, eval=T,echo=TRUE}


```

```{r, eval=T,echo=TRUE}


```

```{r, eval=T,echo=TRUE}


```

```{r, eval=T,echo=TRUE}


```

