---
title: "Week 9 code along"
author: "Niki"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyr)
```

```{r, eval=T,echo=TRUE}
#Slide 8

library(tidyverse)

tidydata <- tribble(
~country,  ~year,  ~cases, ~population,
"Afghanistan",  1999,    745,   19987071,
"Afghanistan",  2000,   2666,   20595360,
"Brazil", 1999, 37737,  172006362)

tidydata

```


```{r, eval=T,echo=TRUE}
#Slide 8

nontidydata <- tribble(
 ~country,~year,~rate,
"Afghanistan",  1999, "745/19987071",
"Afghanistan",  2000, "2666/20595360",
"Brazil", 1999, "37737/172006362",
"Brazil", 1999, "212258/1272915272",
"China", 2000, "213766/1280428583")
nontidydata
```

```{r, eval=T,echo=TRUE}
#Slide 11

nontidydata

tidieddata <- nontidydata %>%
  separate(rate, into = c("cases", "population"),
  sep = "/")

tidieddata

```

```{r, eval=T,echo=TRUE}
#Slide 12

newtidieddata <- tidieddata %>%
  pivot_longer(
    cols = cases:population,
    names_to = "measurement",
    values_to = "value"
  )
newtidieddata

```

```{r, eval=T,echo=TRUE}
#Slide 14

df <- tribble(
  ~id,  ~bp1, ~bp2,
   "A",  100,  120,
   "B",  140,  115,
   "C",  120,  125
) 

df

df %>%
  pivot_longer(
    cols = bp1:bp2,
    names_to = "measurement",
    values_to = "value"
)

```

```{r, eval=T,echo=TRUE}
#Slide 18

newtidieddata

newtidieddata %>%
  pivot_wider(names_from="measurement",
              values_from="value")



```

```{r, eval=T,echo=TRUE}
#Slide 19

df <- tribble(
  ~id, ~measurement, ~value,
  "A",        "bp1",    100,
  "B",        "bp1",    140,
  "B",        "bp2",    115,
  "A",        "bp2",    120,
  "A",        "bp3",    105
) 
df

df %>%
  pivot_wider(
    names_from = measurement,
    values_from = value
  )



```

```{r, eval=T,echo=TRUE}
#Challenge


library(tidyr)

newbillboard <- billboard %>%
  pivot_longer(cols = starts_with("wk"), 
               names_to = "week", 
               values_to = "value")
newbillboard

```

```{r, eval=T,echo=TRUE}
#Challenge

newbillboard <- billboard %>%
  pivot_longer(cols = starts_with("wk"), 
               names_to = "week", 
               values_to = "rank")
newbillboard

```

```{r, eval=T,echo=TRUE}
#Challenge

newbillboard <- billboard %>%
  pivot_longer(cols = starts_with("wk"), 
               names_to = "week", 
               values_to = "rank",
               values_drop_na = T)
newbillboard

```

```{r, eval=T,echo=TRUE}
#Challenge

newbillboard %>%
  mutate(week = parse_number(week))

```


```{r, eval=T,echo=TRUE}
#Challenge

ggplot(newbillboard) +
  aes(x=week,y=rank) +
  geom_point() +
  geom_line(aes(group = rank))+
  theme_bw()
  
```

```{r, eval=T,echo=TRUE}
#Challenge

new_patient <-cms_patient_experience %>%
  pivot_wider(
    names_from = "measure_cd",
    values_from = "prf_rate",
    id_cols = starts_with("org")
    )


new_patient

```

```
